### ISSUE TITLE
run time error python 3.6

### ISSUE THREAD

**Issue by mhmadayad** [BrotherJing/RNN_tabletennis#7]
```

Traceback (most recent call last):
  File "main.py", line 146, in <module>
    tf.app.run(main=main)
  File "/Users/Moh/anaconda/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "main.py", line 101, in main
    model = Model(True, config)
  File "/Users/Moh/Desktop/thesiss/RNN_tabletennis-master/model.py", line 23, in __init__
    self.x = tf.placeholder(tf.float32, shape=[self.batch_size, self.coords, None], name='Input_data')
AttributeError: can't set attribute
```

**Comment by mhmadayad** [comment]
downgrade to python2.7 works fine
